on:
  push:
    branches:
      - Develope
      - Feature
      - main
    paths: ['Terraform/**']
  pull_request:     
      branches:
        - Develope
        - Feature
        - main
      paths: ['Terraform/**']
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - Develope
          - Feature
          - main
     
  
permissions:
 id-token: write
 contents: read
#---------------------
# resuable environment matrix
#---------------------
env:
  ARM_TENANT_ID: ${{ secrets.Tenenat_id }} 
  ARM_USE_OIDC: "true"
  TF_VERSION: "1~1.7"
  

jobs:
  validate:
     name: validate&Scan
     runs-on: ubuntu-latest
   #  strategy:
     #  matrix:
      #   environment: 
          #   - TST
           #  - STG
           #  - PRD
     steps:
        - uses: actions/checkout@v4
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: ${{ env.TF_VERSION }}

        - name: Check if Terraform exists
          run: |
              if command -v terraform >/dev/null 2>&1; then
              echo "Terraform already installed"
              terraform version
              else
              echo "Installing Terraform..."
              sudo apt-get update
              sudo apt-get install -y wget unzip
              wget https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
              unzip terraform_1.7.5_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
              terraform version
              fi

        - name: Terraform Format Check
          run: terraform fmt 

        - name: Terraform Init 
          run: terraform init 

        - name: Terraform Validate
          run: terraform validate
  



 
