on:
  push:
    branches:
      - Develope
      - Feature
      - main
    paths: ['Terraform/**']
  pull_request:     
      branches:
        - Develope
        - Feature
        - main
      paths: ['Terraform/**']
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - Develope
          - Feature
          - main
     
  
permissions:
 id-token: write
 contents: read
#---------------------
# resuable environment matrix
#---------------------
env:
  ARM_TENANT_ID: ${{ secrets.Tenenat_id }} 
  ARM_USE_OIDC: "true"
  TF_VERSION: "1~1.7"

jobs:
  validate:
     name: validate&Scan
     runs-on: ubuntu-latest
     strategy:
       matrix:
         environment: 
             - TST
             - STG
             - PRD
     steps:
        - uses: actions/checkout@v4
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: ${{ env.TF_VERSION }}

        - name: Terraform Format Check
          run: terraform fmt -check -recursive

        - name: Terraform Init (no backend)
          working-directory: environments/${{ matrix.environment }}
          run: terraform init -backend=false

        - name: Terraform Validate
          working-directory: environments/${{ matrix.environment }}
          run: terraform validate
  



 
